### ISSUE TITLE
Review logging output for dockerised front end apps

### ISSUE THREAD

**Issue by mairead** [epimorphics/hmlr-linked-data#56]
As a developer I need to ensure the log format is correctly adhered to 

Business reqs
The Ops checklist specifies JSON format for log output

Spike

- Across 4 LR apps can we check the error, warning, info responses - 404s could be logged as warning rather than error
- Check RequestId propagates from front end app > API > fuseki
- Investigate why PPD application was generating a File object in the logs folder when deployed during git workflows
- Set up cross functional conversation with Ops team 

Timebox: 2 days

Acceptance criteria
- Resolve issue with log file object being generated
- Document any changes required to JSON logger
- Make sure existing logs are correctly formatted

Notes: if an error occurs before json rails logger is initialised you get non-json output - won't fix

**Comment by bogdanadrianmarc** [comment]
After investigation, the issue with the 404s is not related to the JSON logger, but rather how we log errors in each app's code. For example for Regulated Products 404s are logged as `INFO`, while PPD logs 404s as errors: https://github.com/epimorphics/ppd-explorer/blob/master/app/controllers/application_controller.rb

RequestID is implemented in the JSON Logger and is present in the logging output, I will check with the Ops team if it propagates all the way through to the end.

The issue with logs not appearing in terminal is still ongoing and the culprit is Docker not recognising `STDOUT` and defaulting to file logging into `log/production.log`. Logs appear in terminal when reverting to the default logger, which means there's an issue with what file descriptor we provide when initialising the JSON Logger. SSHing into the container and running the command `echo 'test' > /proc/1/fd/1` renders output in container's terminal, while initialising JSON Logger with `'/proc/1/fd/1'` as file descriptor renders no output.
