### ISSUE TITLE
Explore prometheus monitoring requirements for dockerised front end apps

### ISSUE THREAD

**Issue by mairead** [epimorphics/hmlr-linked-data#57]
As a developer I need to add an error count for API connections to help me debug our application stability

**Business reqs**
https://github.com/epimorphics/hmlr-ansible-deployment/issues/70

**Spike**
- Service object handles requests to API. 
- We want to count any non-200 response during API connection requests. We should bracket these into 200s, 300s, 400s etc
- Investigate Prometheus/Rails gem and what does this provide out of the box? See guidance documentation here: https://github.com/prometheus/client_ruby
- Prometheus polls the LR app and we need to hold the error count in server state to be requested. Frequency depends on use case
- The counter will be reset to 0 every time the app is re-deployed so doesn't need to be zero-ed by the application at any point
- We need to define the the value which would trigger an alarm in Prometheus (How large should the count get before a warning appears) - this is defined in the Prometheus config. 
- Can we point Prometheus at something that isn't production?  Prometheus can point at development but we can't run all of Grafana, Prometheus locally for dev work
- Mock the response in the service object to fake error response - either in tests or during development
- Can use Curl to test the Prometheus endpoint and see the value during local development so you can test the Ruby application is exporting the count

**Acceptance criteria**
- Document correct development tasks to complete this request

Timebox: 2 days

**Comment by ijdickinson** [comment]
During discussion on 2022-01-18, we agreed that (if possible), the following metrics would be nice to observe:

- count of HTTP requests, duration, etc (this comes for free with the standard Prometheus middleware for Rack)
- count of data API requests, grouped by status
- a failure to be able to contact the data API at all (as opposed to contacting, but getting a non-200 response)
- anything we can do to leave a trace of an out-of-memory error (might be logging rather than Prometheus metric)
- count of unexpected bad events (to a large extent, this is also what Sentry gives us, but it would be helpful to have a Prometheus metric as well, as the ops team don't tend to monitor Sentry)
