### ISSUE TITLE
Review probe endpoints for dockerised front end apps

### ISSUE THREAD

**Issue by mairead** [epimorphics/hmlr-linked-data#58]
As a developer I need to provide useful handover to the Kubernetes maintainers

**Business request**
The ops team would like us to provide kubernetes probes. The Liveness probe is the only useful probe we can support to prove if the application needs restarting/can receive requests

**Development tasks**
- Copy the live probe that responds with datetime, cache timeout set to 0 so it responds new each time as path '/monitoring/alive'
- Document the Liveness endpoint in the Readme
- Create PR with liveness endpoint as handover to API team

**Acceptance Criteria**
- Endpoint is reachable responds with datetime across 4 land registry apps
- Endpoint is documented in the Readme across 4 land registry apps

Estimate: 1 day

**Comment by andrew-pickin-epi** [comment]
Live probes as a concept are a kubenetes thing. They are intended to identify that the application is stuck and a automatic turn it off, turn it on again is required. There is no such concept in our ec2 vanilla docker deployment such as NRW/HMLR.

In general this containers shouldn't start if the config looks wrong. eg a mandatory environment variable is missing (and probably best not to double guess a default in the image) so fail fast with suitable error message. This should catch the miss-configured deployment case. Ansible deployment, and thus CICD, only cares if the container started successfully. 
Sensu (by default) only cares if the container is running, Prometheus (by default) only cares that metrics are being served.

A equivalent of the kubernetes readiness probes are probably more useful. 

So an endpoint that indicates the application is unable to process requests, so that the container doesn't have subsequent traffic directed to it. This is most likely because it has/is close to exhausting some resource, or has lost contact with some other service. This could be some simple low impact query. As long as the results or predictable (say return code is 200) and it will work once resource/service has recovered, that will be good enough. There is no need for a bespoke endpoint, unless that would give some extra value, but the suitable url/expected response should be documented in the Readme.

**Comment by mairead** [comment]
We decided we don't need this because if we ensure there is a metrics endpoint then at least something will be listening for a connection that will alert if its missing
